### ISSUE TITLE
create-cycle-app has problems with css-loader

### ISSUE THREAD

**Issue by DavidBernal** [cyclejs-community/create-cycle-app#128]
**Code to reproduce the issue:**

Create a new project:

`npx create-cycle-app my-cycle`

Start the project

`cd my-cycle && npm start`

**Expected behavior:**
Run without errors

**Actual behavior:**
Console print errors:
```
ERROR in ./src/css/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/sass-loader/dist/cjs.js??ref--6-2!./node_modules/postcss-loader/src??ref--6-3!./src/css/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (./node_modules/schema-utils/dist/validate.js:88:11)
    at Object.loader (./node_modules/sass-loader/dist/index.js:36:28)
 @ ./src/css/styles.scss 2:26-214 43:4-64:5 46:18-206
 @ multi ./src/index.ts ./src/css/styles.scss

```

**Versions of packages used:**
```
{
  "dependencies": {
    "@cycle/dom": "^22.3.0",
    "@cycle/history": "^7.1.0",
    "@cycle/isolate": "^4.2.0",
    "@cycle/run": "^5.2.0",
    "@cycle/state": "^1.1.0",
    "@cycle/time": "^0.19.0",
    "cyclejs-utils": "^4.0.2",
    "cyclic-router": "^6.0.0",
    "switch-path": "^1.2.0",
    "xstream": "^11.7.0"
  },
  "devDependencies": {
    "@types/mocha": "^5.2.5",
    "cycle-scripts-one-fits-all": ">=6.0.0",
    "cyclejs-test-helpers": "^4.0.0",
    "husky": "^1.2.0",
    "lint-staged": "^8.1.0",
    "prettier": "^1.15.3",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "snabbdom-looks-like": "^1.0.5",
    "snabbdom-pragma": "^2.8.0",
    "webpack": "^4.43.0"
  }
}
```

**Comment by hunnble** [comment]
It seems to be caused by the options change of sass-loader@8(options -> options.sassOptions), downgrading sass-load to 7.x.x solved this problem.
Try `yarn add -D sass-loader@7`.
