### ISSUE TITLE
fails to run at all with crazy const error

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#80]
node version = 6.5.0
create-cycle-app version = 3.0.6 but npm page says lates is 3.0.5 ???

I did this
```
npm install -g create-cycle-app 
npm create-cycle-app my-app --flavor cycle-scripts-one-fits-all
```

I got

```
C:\projects\spikes>C:\Users\steve\AppData\Roaming\npm\node_modules\create-cycle-app\index.js:4
const path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by SteveALee** [comment]
oh, scratch that. nvm-windows has thrown a major wobbly and reset node to 0.12.2.

No idea how other than something may have installed npm directly
