### ISSUE TITLE
Error using create-cycle-app on mac: TypeError: installPackage.indexOf is not a function

### ISSUE THREAD

**Issue by xabitrigo** [cyclejs-community/create-cycle-app#82]
**Code to reproduce the issue:**
$ sudo npm i -g create-cycle-app
$ create-cycle-app my-awesome-app

**Expected behavior:**
App bootstrapped inside my-awesome-app directory

**Actual behavior:**
Error:
```
Creating a new Cycle.js app in /Users/develop/dev/cycle/my-awesome-app.

/usr/local/lib/node_modules/create-cycle-app/src/getPackageName.js:7
  } else if (~installPackage.indexOf('@')) {
                             ^

TypeError: installPackage.indexOf is not a function
    at getPackageName (/usr/local/lib/node_modules/create-cycle-app/src/getPackageName.js:7:30)
    at installScripts (/usr/local/lib/node_modules/create-cycle-app/src/installScripts.js:15:23)
    at preparePackageJson (/usr/local/lib/node_modules/create-cycle-app/src/createApp.js:13:5)
    at preparePackageJson (/usr/local/lib/node_modules/create-cycle-app/src/preparePackageJson.js:21:3)
    at createApp (/usr/local/lib/node_modules/create-cycle-app/src/createApp.js:12:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-cycle-app/index.js:42:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Versions of packages used:**
Macbook Pro
Node: v6.9.5
npm: 3.10.10
create-cycle-app: 3.0.6

**Comment by SteveALee** [comment]
Same on windows :(

all version the same

**Comment by nickbalestra** [comment]
I've published a patch (v3.0.7). Let me know if this fixes it

**Comment by SteveALee** [comment]
Works at treat!
I should have figured was default but late and decided to call it a night :)
