### ISSUE TITLE
cycle-scripts-ts-webpack fails on Windows 10 bash

### ISSUE THREAD

**Issue by brunjick** [cyclejs-community/create-cycle-app#86]
**Code to reproduce the issue:**
`create-cycle-app cycle-ts --flavor cycle-scripts-ts-webpack`

**Expected behavior:**
Successfully finish initialization

**Actual behavior:**
```
/mnt/c/Users/brunjick/Code/cycle-ts/node_modules/cycle-scripts-ts-webpack/scripts/init.js:63
      throw new Error('Unsupported stream library: ' + streamLib)
      ^

Error: Unsupported stream library: false
    at replacements (/mnt/c/Users/brunjick/Code/cycle-ts/node_modules/cycle-scripts-ts-webpack/scripts/ini
t.js:63:13)
    at module.exports (/mnt/c/Users/brunjick/Code/cycle-ts/node_modules/cycle-scripts-ts-webpack/scripts/i
nit.js:166:14)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/create-cycle-app/src/installScripts.js:48:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Versions of packages used:**
0.3.2

**Comment by nickbalestra** [comment]
Thanks @brunjick for reporting this.
The 'cycle-scripts-ts-webpack' flavor is deprecated. Have you tried with [cycle-scripts-one-fits-all](https://github.com/cyclejs-community/create-cycle-app-flavors) instead?

**Comment by brunjick** [comment]
@nickbalestra Thanks, it works 😊 duckduckgo sent me to that package when I searched `create-cycle-app typescript`. google does better job there.
maybe it's a good idea to include deprecated warning in [npm package readme](https://www.npmjs.com/package/cycle-scripts-ts-webpack)?

**Comment by nickbalestra** [comment]
Yes that is a good idea. I'll keep this issue open for that. Thanks again

**Comment by jvanbruegge** [comment]
better to use `npm deprecate`
would do it myself, but I have only publishing rights for the `one-fits-all` flavor
